services:
  ollama:
    image: ollama/ollama
    container_name: codev-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 5

  codev-agent:
    build: .
    container_name: codev-agent
    depends_on:
      ollama:
        condition: service_healthy
    volumes:
      - ./workspace:/app/workspace
      - /var/run/docker.sock:/var/run/docker.sock  # Pour exécution de commandes
    environment:
      - OLLAMA_ENDPOINT=http://ollama:11434
      - RUST_LOG=debug
    networks:
      - codev-network

networks:
  codev-network:
    driver: bridge

volumes:
  ollama_data: